import { afterEach, describe, expect, it, vi } from 'vitest'
import { existsSync, readdirSync, readFileSync, statSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { join } from 'node:path'
import { createHash } from 'node:crypto'
import { DISPLAY_FONT_RULE, displayFontId, displayFontOverride, insertAfterStylesheet, themePreloadLinks } from '../server/utils/displayFonts'
import { DISPLAY_FONTS_DIR, readDisplayFontAssets, stackFamily, systemStack } from '../modules/theme/display-fonts'
import { DISPLAY_FONTS } from '../app/interfaces/site'

const root = fileURLToPath(new URL('..', import.meta.url))
const dir = join(root, DISPLAY_FONTS_DIR)
const assets = readDisplayFontAssets(dir)
const BOGOTA_WEB = ['Archivo', 'JetBrains Mono']
const BOGOTA = {
  family: 'Archivo',
  display: systemStack('"Archivo", "Archivo Fallback", "Helvetica Neue", Arial, sans-serif', BOGOTA_WEB),
  sans: systemStack('"Archivo", "Archivo Fallback", "Helvetica Neue", Arial, sans-serif', BOGOTA_WEB),
}
const STARTER = {
  family: 'Fraunces',
  display: systemStack('"Fraunces", "Fraunces Fallback", "Iowan Old Style", "Palatino Linotype", Georgia, serif', ['Fraunces']),
  sans: systemStack('system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", sans-serif', ['Fraunces']),
}

afterEach(() => vi.restoreAllMocks())

describe('the curated files', () => {
  it('has a font, a fallback section and a version for every value of the Strapi enum', () => {
    for (const id of DISPLAY_FONTS) {
      expect(existsSync(join(dir, `${id}-latin-wght.woff2`)), id).toBe(true)
      expect(assets.versions[id], id).toMatch(/^[\da-f]{8}$/)
      expect(assets.fallbacks[id], id).toContain('size-adjust')
    }
    expect(Object.keys(assets.versions).sort()).toEqual([...DISPLAY_FONTS].sort())
  })

  it('keeps each font at 60 KB or less (ADR 0005, section 8) and ships its OFL', () => {
    const files = readdirSync(dir)
    for (const font of files.filter(file => file.endsWith('.woff2'))) {
      expect(statSync(join(dir, font)).size, font).toBeLessThanOrEqual(60 * 1024)
    }
    expect(files.filter(file => file.startsWith('OFL-')).length).toBe(DISPLAY_FONTS.length)
    for (const file of files.filter(file => file.startsWith('OFL-'))) {
      expect(readFileSync(join(dir, file), 'utf8'), file).toContain('SIL OPEN FONT LICENSE Version 1.1')
    }
  })

  it('has a generated fallback file with its header', () => {
    expect(readFileSync(join(dir, '../display-fallbacks.css'), 'utf8')).toMatch(/^\/\* Generated by scripts\/perf\/font-fallbacks\.py, do not edit by hand\./)
  })
})

describe('provenance', () => {
  const sources = JSON.parse(readFileSync(join(dir, '../display-sources.json'), 'utf8')) as { commit: string, fonts: Record<string, { woff2Sha256: string, oflSha256: string, ttfSha256: string }> }
  const sha256 = (file: string): string => createHash('sha256').update(readFileSync(join(dir, file))).digest('hex')

  it('records a pinned google/fonts commit and the hashes of every source', () => {
    expect(sources.commit).toMatch(/^[\da-f]{40}$/)
    for (const id of DISPLAY_FONTS) {
      expect(sources.fonts[id]?.ttfSha256, id).toMatch(/^[\da-f]{64}$/)
    }
  })

  it.each([...DISPLAY_FONTS])('%s: the committed woff2 and its license match the recorded sha256', (id) => {
    expect(sha256(`${id}-latin-wght.woff2`)).toBe(sources.fonts[id]!.woff2Sha256)
    const license = readdirSync(dir).find(file => file.startsWith('OFL-') && file.toLowerCase().includes(id.replace(/-/g, '')))
    expect(sha256(license!)).toBe(sources.fonts[id]!.oflSha256)
  })
})

describe('theme preloads', () => {
  const fonts = [{ file: 'fraunces-latin-var.woff2', preload: true }, { file: 'mono.woff2', preload: true }, { file: 'lazy.woff2' }]
  const both = '<link rel="preload" href="/fonts/fraunces-latin-var.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/fonts/mono.woff2" as="font" type="font/woff2" crossorigin>'
  it('renders every preloaded font, in order, when nothing overrides the display font', () => {
    expect(themePreloadLinks(fonts, { ...STARTER, file: 'fraunces-latin-var.woff2' }, false)).toBe(both)
  })
  it('leaves out the theme\'s display file when an override is emitted, and only that one', () => {
    expect(themePreloadLinks(fonts, { ...STARTER, file: 'fraunces-latin-var.woff2' }, true)).toBe('<link rel="preload" href="/fonts/mono.woff2" as="font" type="font/woff2" crossorigin>')
  })
  it('keeps it when the body text uses the family, or the theme has no such file', () => {
    expect(themePreloadLinks(fonts, { ...STARTER, file: 'fraunces-latin-var.woff2', sharedWithSans: true }, true)).toBe(both)
    expect(themePreloadLinks(fonts, STARTER, true)).toBe(both)
  })
  it('goes right after the first stylesheet link, or at the end without one', () => {
    expect(insertAfterStylesheet(['<meta><link rel="stylesheet" href="/a.css" crossorigin><link rel="modulepreload">'], '<L>')).toEqual(['<meta><link rel="stylesheet" href="/a.css" crossorigin><L><link rel="modulepreload">'])
    expect(insertAfterStylesheet(['<meta>'], '<L>')).toEqual(['<meta>', '<L>'])
    expect(insertAfterStylesheet(['<meta>'], '')).toEqual(['<meta>'])
  })
})

describe('stack helpers', () => {
  it('drops the theme\'s own web fonts and fallback faces and keeps the system part', () => {
    expect(BOGOTA.display).toBe('"Helvetica Neue", Arial, sans-serif')
    expect(STARTER.display).toBe('"Iowan Old Style", "Palatino Linotype", Georgia, serif')
    expect(STARTER.sans).toBe('system-ui, -apple-system, "Segoe UI", Roboto, "Helvetica Neue", sans-serif')
    expect(stackFamily('"Fraunces", serif')).toBe('Fraunces')
  })
})

describe('displayFontOverride', () => {
  it('emits the face, its fallback faces and --font-display for a font the theme does not use', () => {
    const font = displayFontOverride('newsreader', BOGOTA, assets)!
    expect(font.href).toBe(`/fonts/display/newsreader-latin-wght.woff2?v=${assets.versions.newsreader}`)
    expect(font.css).toMatch(/^@font-face\{font-family:"Newsreader";font-style:normal;font-display:swap;font-weight:200 800;src:url\("\/fonts\/display\/newsreader-latin-wght\.woff2\?v=[\da-f]{8}"\) format\("woff2"\);unicode-range:U\+0000-00FF,/)
    expect(font.css).toContain('font-family:"Newsreader Fallback";font-weight:100 549;src:local("Times New Roman")')
    // serif font on a sans theme: a generic serif stack
    expect(font.css.endsWith(':root{--font-display:"Newsreader","Newsreader Fallback",Georgia,"Times New Roman",serif}')).toBe(true)
    expect(font.css).not.toContain('<')
    expect(DISPLAY_FONT_RULE.test(font.css)).toBe(true)
  })

  it('ends each font\'s stack by its category: sans with the theme\'s sans stack, serif with its serif display stack', () => {
    const stack = (id: string, theme: typeof BOGOTA): string => /--font-display:(.*)\}$/.exec(displayFontOverride(id, theme, assets)!.css)![1]!
    expect(stack('space-grotesk', BOGOTA)).toBe('"Space Grotesk","Space Grotesk Fallback","Helvetica Neue",Arial,sans-serif')
    expect(stack('bricolage-grotesque', STARTER)).toBe('"Bricolage Grotesque","Bricolage Grotesque Fallback",system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",sans-serif')
    expect(stack('newsreader', STARTER)).toBe('"Newsreader","Newsreader Fallback","Iowan Old Style","Palatino Linotype",Georgia,serif')
    expect(stack('fraunces', BOGOTA)).toBe('"Fraunces","Fraunces Fallback",Georgia,"Times New Roman",serif')
    expect(stack('archivo', { family: 'X', display: '', sans: 'cursive' })).toBe('"Archivo","Archivo Fallback",system-ui,sans-serif')
  })

  it('matches the snapshot of one font (versions masked)', () => {
    expect(displayFontOverride('space-grotesk', STARTER, assets)!.css.replace(/\?v=[\da-f]{8}/, '?v=VERSION')).toMatchInlineSnapshot(`"@font-face{font-family:"Space Grotesk";font-style:normal;font-display:swap;font-weight:300 700;src:url("/fonts/display/space-grotesk-latin-wght.woff2?v=VERSION") format("woff2");unicode-range:U+0000-00FF,U+0131,U+0152-0153,U+02BB-02BC,U+02C6,U+02DA,U+02DC,U+0300-0304,U+0308,U+0329,U+2000-206F,U+20AC,U+2122,U+2190-2193,U+2212,U+2215,U+FEFF,U+FFFD}@font-face{font-family:"Space Grotesk Fallback";font-weight:100 549;src:local("Arial"),local("ArialMT"),local("Liberation Sans"),local("Arimo");size-adjust:110.89%;ascent-override:88.73%;descent-override:26.33%;line-gap-override:0%}@font-face{font-family:"Space Grotesk Fallback";font-weight:550 900;src:local("Arial Bold"),local("Arial-BoldMT"),local("Liberation Sans Bold"),local("Arimo Bold");size-adjust:102.47%;ascent-override:96.03%;descent-override:28.50%;line-gap-override:0%}:root{--font-display:"Space Grotesk","Space Grotesk Fallback",system-ui,-apple-system,"Segoe UI",Roboto,"Helvetica Neue",sans-serif}"`)
  })

  it.each([...DISPLAY_FONTS])('emits %s for one theme and nothing for the theme that already uses it', (id) => {
    const results = [BOGOTA, STARTER].map(theme => displayFontOverride(id, theme, assets))
    expect(results.filter(Boolean)).toHaveLength(id === 'archivo' || id === 'fraunces' ? 1 : 2)
    for (const result of results) if (result) expect(DISPLAY_FONT_RULE.test(result.css)).toBe(true)
  })

  it('emits nothing when the font is the theme\'s own (case-insensitive)', () => {
    expect(displayFontOverride('archivo', BOGOTA, assets)).toBeNull()
    expect(displayFontOverride('fraunces', STARTER, assets)).toBeNull()
    expect(displayFontOverride('fraunces', { ...STARTER, family: 'FRAUNCES' }, assets)).toBeNull()
  })

  it.each([undefined, '', 'comic-sans', 'Newsreader', '__proto__', 'constructor', 'newsreader;}</style><script>', 'archivo '])('emits nothing for %j', (value) => {
    expect(displayFontOverride(value, BOGOTA, assets)).toBeNull()
  })

  it('emits nothing when the build has no file or fallback for the font', () => {
    expect(displayFontOverride('newsreader', BOGOTA, { versions: {}, fallbacks: assets.fallbacks })).toBeNull()
    expect(displayFontOverride('newsreader', BOGOTA, { versions: assets.versions, fallbacks: {} })).toBeNull()
  })

  it('gates the CSS: a stack or a version that breaks the shape is left out and logged', () => {
    const error = vi.spyOn(console, 'error').mockImplementation(() => {})
    expect(displayFontOverride('space-grotesk', { ...BOGOTA, sans: 'sans-serif}</style><script>alert(1)</script>, sans-serif' }, assets)).toBeNull()
    expect(displayFontOverride('newsreader', BOGOTA, { versions: { newsreader: '"};x' }, fallbacks: assets.fallbacks })).toBeNull()
    expect(displayFontOverride('newsreader', BOGOTA, { versions: assets.versions, fallbacks: { newsreader: 'body{display:none}' } })).toBeNull()
    expect(error).toHaveBeenCalledTimes(3)
  })
})

describe('displayFontId', () => {
  it('accepts the enum values only', () => {
    expect(displayFontId('fraunces')).toBe('fraunces')
    expect(displayFontId('toString')).toBeUndefined()
    expect(displayFontId(3)).toBeUndefined()
  })
})
