// Generates docs/themes/reference/ from the contract (ADR 0005, section 6): roles, layout, hooks and slots.
// `npm run theme:reference` writes it; `npm run lint:reference` (part of `npm run lint`) fails when a file is out of date.
import { existsSync, mkdirSync, readdirSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { CONTRACT_VERSION } from '../modules/theme/contract'
import { CONTRAST_RULES } from '../modules/theme/contrast'
import type { ContrastRule, LayoutRegion } from '../modules/theme/types'
import { DEFAULT_LAYOUT, SLOT_SPECS } from '../modules/theme/data'
import { LAYOUT_REGIONS, SLOT_NAMES } from '../modules/theme/constants'
import { REGION_VARIANTS, VARIANT_DESCRIPTIONS } from '../modules/theme/layout/variants'
import { OPTIONAL_ROLES, REQUIRED_ROLES, ROLE_PURPOSES, TYPE_FAMILIES, TYPE_STEPS } from '../modules/theme/roles.mjs'
import type { RoleGroup } from '../modules/theme/roles.mjs'
import hooks from '../app/theme/hooks.json'

const DIR = fileURLToPath(new URL('../docs/themes/reference/', import.meta.url))
const COMMAND = '`npm run theme:reference`'
const HEADER = `<!-- Generated by ${COMMAND} from the theme contract (modules/theme/, app/theme/). Do not edit by hand. -->`

interface HookEntry {
  describes: string
  layouts?: Record<string, string[]>
  states?: string[]
}

interface AttributeEntry {
  describes: string
  values: string | string[]
}

const HOOK_CLASSES = hooks.classes as Record<string, string | HookEntry>
const HOOK_ATTRIBUTES = hooks.attributes as Record<string, AttributeEntry>

function cell(text: string): string {
  return text.split(/(`[^`]*`)/).map(part => part.startsWith('`') ? part : part.replace(/<([\w-]+)>/g, '`<$1>`')).join('').replaceAll('|', '\\|')
}

function code(items: string[]): string {
  return items.map(item => `\`${item}\``).join(', ')
}

function table(head: string[], rows: string[][]): string {
  const line = (cols: string[]): string => `| ${cols.map(cell).join(' | ')} |`
  return [line(head), line(head.map(() => '---')), ...rows.map(line)].join('\n')
}

function page(title: string, intro: string, body: string[]): string {
  return `${HEADER}\n\n# ${title}\n\n${intro}\n\n${body.join('\n\n')}\n`
}

function hook(name: string): HookEntry {
  const entry = HOOK_CLASSES[name]!
  return typeof entry === 'string' ? { describes: entry } : entry
}

function rulesOf(role: string): { foreground: ContrastRule[], background: ContrastRule[] } {
  return {
    foreground: CONTRAST_RULES.filter(rule => rule.role === role),
    background: CONTRAST_RULES.filter(rule => rule.role !== role && rule.surfaces.includes(role)),
  }
}

function ratio(rule: ContrastRule): string {
  return `≥ ${rule.min}:1`
}

function textOn(role: string): string {
  const parts = rulesOf(role).foreground.map(rule => `${code(rule.surfaces)} ${ratio(rule)}`)
  return parts.length ? parts.join('; ') : 'none'
}

function backgroundFor(role: string): string {
  const { background } = rulesOf(role)
  const parts = [...new Set(background.map(rule => rule.min))].map(min => `${code(background.filter(rule => rule.min === min).map(rule => rule.role))} ≥ ${min}:1`)
  return parts.length ? parts.join('; ') : 'none'
}

const GROUP_INTRO: Record<RoleGroup, string> = {
  color: 'Color roles. A `value` is one string or one value per mode id; contrast is checked in every mode.',
  shadow: 'Shadow and glow roles. A `value` may be `none`, and may be one string or one value per mode id.',
  spacing: 'Space scale and page rhythm. `at` gives responsive values.',
  radius: 'Corner radii.',
  size: 'Widths and heights of the page.',
  motion: 'Durations and easing curves.',
}

function roles(): string {
  const body: string[] = []
  for (const group of Object.keys(REQUIRED_ROLES) as RoleGroup[]) {
    const optional = group === 'color' || group === 'shadow' ? OPTIONAL_ROLES[group] : {}
    const rows = [
      ...REQUIRED_ROLES[group].map(name => [`\`${name}\``, 'required', ROLE_PURPOSES[name]!, textOn(name), backgroundFor(name)]),
      ...Object.entries(optional).map(([name, value]) => [`\`${name}\``, `optional, core default \`${value}\``, ROLE_PURPOSES[name]!, textOn(name), backgroundFor(name)]),
    ]
    body.push(`## \`${group}\`\n\n${GROUP_INTRO[group]}\n\n${table(['Role', 'Required', 'Purpose', 'As text or control on', 'As background for'], rows)}`)
  }
  const families = TYPE_FAMILIES.map(family => `\`${family}\``).join(', ')
  const steps = TYPE_STEPS.map(step => [`\`${step}\``, `\`--text-${step}\``, `\`--tracking-${step}\``])
  body.push(`## \`type\`\n\n${[
    `Font families (\`type.families\`, all required): ${families}. Each generates \`--font-<family>\`.`,
    `The scale needs every step below, in \`type.groups\`; a group's \`family\` must be one of the families.\n\n${table(['Step', 'Font shorthand (weight, size, line height, family)', 'Letter spacing'], steps)}`,
  ].join('\n\n')}`)
  return page(
    'Roles',
    `Roles of contract v${CONTRACT_VERSION}, by \`theme.json\` group. Contrast (the last two columns: the role as foreground on those surfaces, and the foregrounds checked on the role) is checked per mode by \`npm run theme:check\` (WCAG 2 AA; text 4.5:1, controls and focus 3:1); an optional role a theme omits is checked with its core default. Guide: [../creating-a-theme.md](../creating-a-theme.md).`,
    body,
  )
}

function variantsOnly(region: LayoutRegion, variant: string): string[] {
  const all = REGION_VARIANTS[region].variants
  return Object.keys(HOOK_CLASSES).filter((name) => {
    const variants = hook(name).layouts?.[region]
    return variants && variants.includes(variant) && variants.length < all.length
  })
}

function layout(): string {
  const body: string[] = []
  for (const region of LAYOUT_REGIONS) {
    const { component, variants } = REGION_VARIANTS[region]
    const rows = variants.map((variant) => {
      const only = variantsOnly(region, variant)
      return [
        `\`${variant}\`${variant === DEFAULT_LAYOUT[region] ? ' (default)' : ''}`,
        VARIANT_DESCRIPTIONS[region][variant]!,
        only.length ? code(only) : 'none',
      ]
    })
    body.push(`## \`${region}\`\n\nComponent \`${component}\`. The root element carries \`data-layout="<variant>"\`.\n\n${table(['Variant', 'Description', 'Hooks only in this variant'], rows)}`)
  }
  return page(
    'Layout',
    'Regions of the site and the variants the core implements, chosen under `layout` in `theme.json`. An omitted region uses its default, the first variant. A name outside this list fails validation. Every installed theme styles every variant. In `theme.css`, select a hook together with the variant (`.myc-header[data-layout="centered"] .myc-nav-link`) when a rule is meant for one of them. Hooks that appear in every variant of their region are in [hooks.md](hooks.md).',
    body,
  )
}

function hooksPage(): string {
  const attributes = Object.entries(HOOK_ATTRIBUTES).map(([name, { describes, values }]) => [
    `\`${name}\``,
    describes,
    Array.isArray(values) ? code(values) : values,
  ])
  const names = Object.keys(HOOK_CLASSES)
  const classRows = (list: string[], region?: LayoutRegion): string[][] => list.map((name) => {
    const { describes, states, layouts } = hook(name)
    const row = [`\`${name}\``, describes, states ? code(states) : '']
    if (region) {
      const variants = layouts![region]!
      row.push(variants.length === REGION_VARIANTS[region].variants.length ? 'every variant' : code(variants))
    }
    return row
  })
  const body = [`## Attributes\n\n${table(['Attribute', 'Describes', 'Values'], attributes)}`]
  for (const region of LAYOUT_REGIONS) {
    const list = names.filter(name => region in (hook(name).layouts ?? {}))
    if (list.length) body.push(`## Classes of \`${region}\`\n\n${table(['Class', 'Describes', 'States', 'Variants'], classRows(list, region))}`)
  }
  const general = names.filter(name => !hook(name).layouts)
  body.push(`## General classes\n\nThese appear in every layout variant.\n\n${table(['Class', 'Describes', 'States'], classRows(general))}`)
  return page(
    'Hooks',
    `Public styling hooks of contract v${CONTRACT_VERSION}, from \`app/theme/hooks.json\`. A theme's \`theme.css\` and slot CSS may select only these \`myc-*\` classes and core \`data-*\` attributes; every other one is internal and can change in any release. Adding a hook stays in contract v${CONTRACT_VERSION}; removing or renaming one is a contract change. A state is a class or attribute the hook takes.`,
    body,
  )
}

function slots(): string {
  const body = SLOT_NAMES.map((name) => {
    const { purpose, props, defaultRenders } = SLOT_SPECS[name]
    const propsText = props.length
      ? table(['Prop', 'Type', 'Required', 'Description'], props.map(prop => [`\`${prop.name}\``, `\`${prop.type}\``, prop.optional ? 'no' : 'yes', prop.description ?? '']))
      : 'No props.'
    return `## \`${name}\`\n\n${purpose}\n\n${propsText}\n\n- Core default: ${defaultRenders}`
  })
  return page(
    'Slots',
    'Vue components for what CSS cannot express. The list is closed. A theme ships one as `slots/<Name>.vue`; without the file, the core default in `app/theme/defaults/` renders. A slot is static by default and has no `<style>` block; declare `"island": true` under `slots` in `theme.json` when it needs JavaScript ([ADR 0005](../../adr/0005-theme-contract.md), section 12). Every slot may be an island. Guide: [../creating-a-theme.md](../creating-a-theme.md).',
    body,
  )
}

function index(): string {
  return page(
    'Theme reference',
    `Reference of theme contract v${CONTRACT_VERSION}, generated from the code. To change it, change the contract and run ${COMMAND}; \`npm run lint\` fails when these files are out of date. How to build a theme: [../creating-a-theme.md](../creating-a-theme.md); the decision: [ADR 0005](../../adr/0005-theme-contract.md).`,
    [[
      '- [Roles](roles.md): every role of `theme.json`, its purpose, default and contrast rules, and the type scale.',
      '- [Layout](layout.md): regions and their variants.',
      '- [Hooks](hooks.md): the `myc-*` classes and `data-*` attributes a theme may style.',
      '- [Slots](slots.md): the components a theme may replace, with their props and defaults.',
    ].join('\n')],
  )
}

function referenceFiles(): Record<string, string> {
  return {
    'README.md': index(),
    'roles.md': roles(),
    'layout.md': layout(),
    'hooks.md': hooksPage(),
    'slots.md': slots(),
  }
}

const files = referenceFiles()
const present = existsSync(DIR) ? readdirSync(DIR) : []
const extra = present.filter(name => !(name in files))

if (process.argv.includes('--check')) {
  const problems = [
    ...Object.entries(files).flatMap(([name, content]) => {
      if (!present.includes(name)) return [`${name} is missing`]
      return readFileSync(DIR + name, 'utf8') === content ? [] : [`${name} is out of date`]
    }),
    ...extra.map(name => `${name} is not generated (run npm run theme:reference to remove it)`),
  ]
  if (problems.length) {
    process.stderr.write(`docs/themes/reference/: ${problems.join('; ')}. Run \`npm run theme:reference\` and commit the result.\n`)
    process.exit(1)
  }
  process.stdout.write('docs/themes/reference/ is up to date\n')
} else {
  mkdirSync(DIR, { recursive: true })
  for (const name of extra) rmSync(DIR + name, { recursive: true, force: true })
  for (const [name, content] of Object.entries(files)) writeFileSync(DIR + name, content)
  process.stdout.write('docs/themes/reference/ generated\n')
}
