"""Generates a theme's font-fallbacks.css: local fallback faces sized to the web fonts.

Each weight and width range gets its own face, sized against the variable font at that instance, so
text keeps its line breaks when the web font swaps in. Method and numbers: docs/performance.md.

    pip install fonttools brotli
    python3 scripts/perf/font-fallbacks.py [--theme bogota] [ARIAL_REGULAR ARIAL_BOLD MONO_REGULAR]
    python3 scripts/perf/font-fallbacks.py --theme starter [TIMES_REGULAR TIMES_BOLD]

The metric files default to Liberation Sans and Liberation Mono, which share Arial's and Courier
New's advance widths; the starter uses Liberation Serif, which shares Times New Roman's.
"""

import argparse
from pathlib import Path

from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / 'themes/bogota/font-fallbacks.css'
FONTS = ROOT / 'themes/bogota/fonts'
STARTER_OUT = ROOT / 'themes/starter/font-fallbacks.css'
STARTER_FONTS = ROOT / 'themes/starter/fonts'

TIMES = 'local("Times New Roman"), local("TimesNewRomanPSMT"), local("Liberation Serif"), local("Tinos")'
TIMES_BOLD = 'local("Times New Roman Bold"), local("TimesNewRomanPS-BoldMT"), local("Liberation Serif Bold"), local("Tinos Bold")'
# Starter: (font-weight range, Fraunces wght it is sized at, bold fallback)
STARTER_WEIGHTS = [('100 549', 400, False), ('550 900', 600, True)]
HEADER = ('/* Generated by scripts/perf/font-fallbacks.py, do not edit by hand.\n'
          '   Local fallbacks sized to the web fonts, so the swap does not reflow text (docs/performance.md) */\n\n')

# English letter frequencies (%), the weighting capsize and fontaine use for average width
FREQUENCIES = {
    ' ': 18.3, 'e': 10.2, 't': 7.5, 'a': 6.5, 'o': 6.2, 'i': 5.7, 'n': 5.7, 's': 5.3, 'r': 5.0,
    'h': 4.9, 'l': 3.3, 'd': 3.3, 'u': 2.3, 'c': 2.2, 'm': 2.0, 'f': 1.8, 'g': 1.6, 'w': 1.7,
    'p': 1.5, 'y': 1.4, 'b': 1.3, 'v': 0.8, 'k': 0.6, 'x': 0.15, 'j': 0.1, 'q': 0.1, 'z': 0.07,
}

ARIAL = 'local("Arial"), local("ArialMT"), local("Liberation Sans"), local("Arimo")'
ARIAL_BOLD = 'local("Arial Bold"), local("Arial-BoldMT"), local("Liberation Sans Bold"), local("Arimo Bold")'
COURIER = 'local("Courier New"), local("CourierNewPSMT"), local("Liberation Mono"), local("Cousine")'

# (font-weight range, Archivo wght it is sized at, bold fallback)
WEIGHTS = [('100 349', 300, False), ('350 449', 400, False), ('450 549', 500, False),
           ('550 649', 600, True), ('650 900', 700, True)]
# (font-stretch range or None for normal, Archivo wdth it is sized at)
WIDTHS = [(None, 100), ('106% 118%', 112), ('119% 125%', 125)]


def average_width(font: TTFont) -> float:
    cmap = font.getBestCmap()
    advances = font['hmtx']
    total = sum(advances[cmap[ord(char)]][0] * weight for char, weight in FREQUENCIES.items())
    return total / sum(FREQUENCIES.values()) / font['head'].unitsPerEm


def instance(path: Path, axes: dict) -> TTFont:
    return instantiateVariableFont(TTFont(path), axes)


def face(family: str, src: str, size: float, ascent: float, descent: float,
         weight: str | None = None, stretch: str | None = None) -> str:
    lines = [f'    font-family: "{family}";']
    if weight:
        lines.append(f'    font-weight: {weight};')
    if stretch:
        lines.append(f'    font-stretch: {stretch};')
    lines += [
        f'    src: {src};',
        f'    size-adjust: {size * 100:.2f}%;',
        f'    ascent-override: {ascent / size * 100:.2f}%;',
        f'    descent-override: {descent / size * 100:.2f}%;',
        '    line-gap-override: 0%;',
    ]
    return '@font-face {\n' + '\n'.join(lines) + '\n}\n'


def starter(metrics: list[str]) -> None:
    serif, serif_bold = (Path(p) for p in (metrics if len(metrics) == 2 else (
        '/usr/share/fonts/liberation-serif-fonts/LiberationSerif-Regular.ttf',
        '/usr/share/fonts/liberation-serif-fonts/LiberationSerif-Bold.ttf',
    )))
    regular_width = average_width(TTFont(serif))
    bold_width = average_width(TTFont(serif_bold))
    path = STARTER_FONTS / 'fraunces-latin-var.woff2'
    fraunces = TTFont(path)
    em = fraunces['head'].unitsPerEm
    ascent, descent = fraunces['hhea'].ascent / em, -fraunces['hhea'].descent / em
    faces = []
    for weight, wght, bold in STARTER_WEIGHTS:
        size = average_width(instance(path, {'wght': wght})) / (bold_width if bold else regular_width)
        faces.append(face('Fraunces Fallback', TIMES_BOLD if bold else TIMES, size, ascent, descent, weight))
    STARTER_OUT.write_text(HEADER + '\n'.join(faces))
    print(f'{STARTER_OUT.relative_to(ROOT)} generated ({len(faces)} faces)')


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument('--theme', choices=['bogota', 'starter'], default='bogota')
    parser.add_argument('metrics', nargs='*', help='metric font files (3 for bogota, 2 for starter), optional')
    args = parser.parse_args()
    if args.theme == 'starter':
        return starter(args.metrics)
    sans, sans_bold, mono = (Path(p) for p in (args.metrics if len(args.metrics) == 3 else (
        '/usr/share/fonts/liberation-sans-fonts/LiberationSans-Regular.ttf',
        '/usr/share/fonts/liberation-sans-fonts/LiberationSans-Bold.ttf',
        '/usr/share/fonts/liberation-mono-fonts/LiberationMono-Regular.ttf',
    )))
    regular_width = average_width(TTFont(sans))
    bold_width = average_width(TTFont(sans_bold))

    archivo = TTFont(FONTS / 'archivo-latin-var.woff2')
    archivo_em = archivo['head'].unitsPerEm
    ascent, descent = archivo['hhea'].ascent / archivo_em, -archivo['hhea'].descent / archivo_em

    faces = []
    for stretch, wdth in WIDTHS:
        for weight, wght, bold in WEIGHTS:
            width = average_width(instance(FONTS / 'archivo-latin-var.woff2', {'wght': wght, 'wdth': wdth}))
            size = width / (bold_width if bold else regular_width)
            faces.append(face('Archivo Fallback', ARIAL_BOLD if bold else ARIAL, size, ascent, descent, weight, stretch))

    jetbrains = TTFont(FONTS / 'jetbrains-mono-latin-var.woff2')
    jetbrains_em = jetbrains['head'].unitsPerEm
    size = average_width(instance(FONTS / 'jetbrains-mono-latin-var.woff2', {'wght': 400})) / average_width(TTFont(mono))
    faces.append(face('JetBrains Mono Fallback', COURIER, size,
                      jetbrains['hhea'].ascent / jetbrains_em, -jetbrains['hhea'].descent / jetbrains_em))

    OUT.write_text(HEADER + '\n'.join(faces))
    print(f'{OUT.relative_to(ROOT)} generated ({len(faces)} faces)')


if __name__ == '__main__':
    main()
